name: packwiz-serve

services:
  server:
    build: ./server
    volumes:
      - ./pack:/pack
    ports: [8080:80]

  installer:
    build: ./installer
    volumes:
      - ./install:/data
    depends_on: [server]
    environment:
      PACKWIZ_URL: http://server
