map $http_accept $detect_type {
   default application/octet-stream;
   ~text text/plain;
}

server {
   listen 80;

   root /pack;
   try_files $uri /pack.toml;
   default_type $detect_type;

   include /etc/nginx/extra-conf.d/*.conf;
}